name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - '**'
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'        # Specify the Java version
        distribution: 'temurin'   # Specify the JDK distribution (temurin is commonly used)

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Install dependencies
      run: mvn install

    - name: Run unit tests
      run: mvn test
